# Generated by Django 6.0.3 on 2026-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('venue_owner', 'Venue Owner'), ('manager', 'Manager'), ('performer', 'Performer'), ('fan', 'Fan')], max_length=20, null=True),
        ),
    ]
