# Generated by Django 6.0.3 on 2026-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_interests_user_music_style_user_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='soundcloud_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
    ]
