# Generated by Django 4.2.30 on 2026-04-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
