# Generated by Django 6.0.4 on 2026-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performers", "0002_alter_collaborationrequest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborationrequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
