# Generated by Django 6.0.3 on 2026-04-23 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0007_gigapplication_verification'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('fan', 'Fan'), ('performer', 'Performer'), ('venue', 'Venue')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='gigs.gigapplication')),
                ('reviewed_performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewed_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='venues.venue')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('reviewing_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='venues.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reviewed_performer__isnull', False), ('reviewing_venue__isnull', True)), fields=('reviewer', 'reviewed_performer'), name='unique_user_performer_review'), models.UniqueConstraint(condition=models.Q(('reviewed_venue__isnull', False)), fields=('reviewer', 'reviewed_venue'), name='unique_user_venue_review'), models.UniqueConstraint(condition=models.Q(('reviewed_performer__isnull', False), ('reviewing_venue__isnull', False)), fields=('reviewing_venue', 'reviewed_performer'), name='unique_venue_performer_review')],
            },
        ),
    ]
