# Generated by Django 6.0.4 on 2026-04-07 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GigListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("venue_name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("pay", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("open_format", "Open Format"),
                            ("house", "House"),
                            ("hip_hop", "Hip Hop"),
                            ("edm", "EDM"),
                            ("acoustic", "Acoustic"),
                            ("band", "Live Band"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gig_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
