# Generated by Django 4.2.30 on 2026-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_giglisting_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giglisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
