# Generated by Django 6.0.4 on 2026-04-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0003_alter_giglisting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giglisting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
