# Generated by Django 6.0.3 on 2026-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_alter_giglisting_id_gigapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigapplication',
            name='performer_verified_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gigapplication',
            name='venue_verified_complete',
            field=models.BooleanField(default=False),
        ),
    ]
