# Generated by Django 6.0.4 on 2026-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0008_alter_gigapplication_id_alter_giglisting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gigapplication",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="giglisting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
