# Generated by Django 6.0.3 on 2026-05-05 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_alter_gigapplication_id_alter_giglisting_id'),
        ('notifications', '0005_collab_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notifications_unique_recipient_type_application',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'notification_type', 'related_application')},
        ),
    ]
